services:
  webapp:
    container_name: webapp
    extends:
      file: ./webapp/compose.yaml
      service: webapp

  nginx:
    container_name: nginx
    extends:
      file: ./nginx/compose.yaml
      service: nginx
